workflows:
  build-expo-android:
    name: Expo Build for Android
    max_build_duration: 20
    environment:
      node: 18.16.0
      java: 11
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build APK with EAS
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
