workflows:
  build-expo-android:
    name: Expo Build for Android
    max_build_duration: 20
    environment:
      node: 18.16.0
      java: 11
      expo-cli: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Login to Expo (optional if not using EAS)
        script: |
          npx expo login --username=$EXPO_USERNAME --password=$EXPO_PASSWORD
      - name: Build APK with EAS
        script: |
          npm install -g eas-cli
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
