workflows:
  build-android:
    name: Build Fierté RDC APK
    max_build_duration: 20
    environment:
      vars:
        PACKAGE_NAME: "com.fierterdc.app"
      node: 18.16.0
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
