workflows:
  build-expo-android:
    name: Expo APK build
    max_build_duration: 20
    environment:
      node: 18.16.0
      java: 11
      groups:
        - build
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Log in to Expo with token
        script: |
          export EXPO_TOKEN=$EXPO_TOKEN
          npx eas whoami || echo "Using Expo Token"
      - name: Build APK with EAS (uses EXPO_TOKEN env automatically)
        script: |
          eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
